spring:
  application:
    name: "hufs"
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/hufs/testdb;MODE=Oracle
    username: sa
    password: sa
    hikari:
      jdbc-url: jdbc:h2:~/hufs/testdb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${LOCAL_REDIS_URL}
      port: ${LOCAL_REDIS_PORT}

jwt:
  secret:
    key: ${JWT_ACCESS_TOKEN_SECRET_KEY}
    expired:
      time: ${JWT_ACCESS_TOKEN_EXPIRED_TIME}

springdoc:
  api-docs:
    version: openapi_3_0
    path: /public-api/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /public-api/swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match:
    - /**